# Generated by Django 3.1.13 on 2021-09-11 10:16

from django.db import migrations, models
import pokemon_entities.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(max_length=200, null=True, storage=pokemon_entities.custom_storage.OverwriteStorage(), upload_to=''),
        ),
    ]
