# Generated by Django 3.1.13 on 2021-09-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    def copy_fields_content(apps, schema_editor):
        fields_to_update = ['lat', 'lon']
        PokemonEntity = apps.get_model('pokemon_entities', 'PokemonEntity')
        db_alias = schema_editor.connection.alias

        PokemonPEntity = apps.get_model('pokemon_entities', 'PokemonPEntity')

        pokemon_entities = (PokemonEntity.objects.using(db_alias)
                            .values(*fields_to_update))

        PokemonPEntity.objects.using(db_alias).bulk_create([
            PokemonPEntity(**q) for q in pokemon_entities
        ])

    dependencies = [
        ('pokemon_entities', '0004_create_intermediary_model'),
    ]

    operations = [
        migrations.RunPython(copy_fields_content,
                             reverse_code=migrations.RunPython.noop)
    ]
