# Generated by Django 3.1.13 on 2021-09-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_data_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonEntity',
        ),
    ]
