# Generated by Django 3.1.13 on 2021-09-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_drop_null_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_pokemonentities', to='pokemon_entities.pokemon', verbose_name='разновидность покемона'),
        ),
    ]
